### ISSUE TITLE
How to host my own Mangazuna API?

### ISSUE THREAD

**Issue by corinloch** [LuckyIndraEfendi/Mangazuna#2]
is it possible to host my own Mangazuna API locally?

**Comment by corinloch** [comment]
And is it possible to change language to english? Thanks!

**Comment by LuckyIndraEfendi** [comment]
> And is it possible to change language to english? Thanks!

I can't change it to English because the API I'm using provides manga data in Indonesian.

**Comment by LuckyIndraEfendi** [comment]
> is it possible to host my own Mangazuna API locally?

Sorry but for now I can't give my private API access to the public.
